uint8 select
parsian_msgs/parsian_skill_gotoPoint gotoPointTask
parsian_msgs/parsian_skill_gotoPointAvoid gotoPointAvoidTask
parsian_msgs/parsian_skill_kick kickTask
parsian_msgs/parsian_skill_oneTouch oneTouchTask
parsian_msgs/parsian_skill_receivePass receivePassTask
parsian_msgs/parsian_skill_no noTask

uint8 GOTOPOINT = 0

uint8 GOTOPOINTAVOID = 1

uint8 KICK = 2

uint8 ONETOUCH = 3

uint8 RECIVEPASS = 4

uint8 NOTASK = 5
